# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_experimental_tensor_relu_reshape <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_relu_reshape`, input)
}

cpp_experimental_tensor_sizes <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_sizes`, input)
}

cpp_experimental_tensor_generated_methods <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_generated_methods`, input)
}

cpp_experimental_tensor_native_integer_argument <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_native_integer_argument`, input)
}

cpp_experimental_tensor_native_bool_return <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_native_bool_return`, input)
}

cpp_experimental_tensor_metadata <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_metadata`, input)
}

cpp_experimental_tensor_shape_pipeline <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_shape_pipeline`, input)
}

cpp_experimental_tensor_reductions <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_reductions`, input)
}

cpp_experimental_tensor_comparisons <- function(first, second) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_comparisons`, first, second)
}

cpp_experimental_namespace_out_overload <- function(first, second) {
    .Call(`_torchextensiontest_cpp_experimental_namespace_out_overload`, first, second)
}

cpp_experimental_tensor_to_dtype <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_to_dtype`, input)
}

cpp_experimental_tensor_autograd_state <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_autograd_state`, input)
}

cpp_experimental_tensor_scalar_overloads <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_scalar_overloads`, input)
}

cpp_experimental_tensor_inplace_overloads <- function(input, other) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_inplace_overloads`, input, other)
}

cpp_experimental_tensor_cat_overloads <- function(first, second) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_cat_overloads`, first, second)
}

cpp_public_torch_namespace_functions <- function(first, second) {
    .Call(`_torchextensiontest_cpp_public_torch_namespace_functions`, first, second)
}

cpp_public_torch_nested_namespace_functions <- function(input) {
    .Call(`_torchextensiontest_cpp_public_torch_nested_namespace_functions`, input)
}

cpp_experimental_tensor_to_device <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_tensor_to_device`, input)
}

cpp_experimental_creation_zeros <- function() {
    .Call(`_torchextensiontest_cpp_experimental_creation_zeros`)
}

cpp_experimental_creation_arange <- function() {
    .Call(`_torchextensiontest_cpp_experimental_creation_arange`)
}

cpp_experimental_creation_eye <- function() {
    .Call(`_torchextensiontest_cpp_experimental_creation_eye`)
}

cpp_experimental_creation_full_like <- function(input) {
    .Call(`_torchextensiontest_cpp_experimental_creation_full_like`, input)
}

cpp_experimental_creation_random_sizes <- function() {
    .Call(`_torchextensiontest_cpp_experimental_creation_random_sizes`)
}

zeros <- function(rows, cols) {
    .Call(`_torchextensiontest_zeros`, rows, cols)
}

cpp_experimental_nn2poly_linear <- function(layer, coefficients) {
    .Call(`_torchextensiontest_cpp_experimental_nn2poly_linear`, layer, coefficients)
}

cpp_experimental_nn2poly_add_partition <- function(matrix, column, scalar, values) {
    .Call(`_torchextensiontest_cpp_experimental_nn2poly_add_partition`, matrix, column, scalar, values)
}

cpp_experimental_nn2poly_add_poly_eval <- function(matrix, column, input, input_column, coefficients) {
    .Call(`_torchextensiontest_cpp_experimental_nn2poly_add_poly_eval`, matrix, column, input, input_column, coefficients)
}

cpp_experimental_nn2poly_accumulate_partition <- function(matrix, output_column, input_columns, multipliers, output) {
    .Call(`_torchextensiontest_cpp_experimental_nn2poly_accumulate_partition`, matrix, output_column, input_columns, multipliers, output)
}

