// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_experimental_tensor_relu_reshape
torch::experimental::Tensor cpp_experimental_tensor_relu_reshape(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_relu_reshape(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_relu_reshape(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_sizes
std::vector<std::int64_t> cpp_experimental_tensor_sizes(SEXP input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_sizes(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_sizes(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_generated_methods
torch::experimental::Tensor cpp_experimental_tensor_generated_methods(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_generated_methods(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_generated_methods(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_native_integer_argument
torch::experimental::Tensor cpp_experimental_tensor_native_integer_argument(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_native_integer_argument(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_native_integer_argument(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_native_bool_return
bool cpp_experimental_tensor_native_bool_return(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_native_bool_return(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_native_bool_return(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_metadata
Rcpp::List cpp_experimental_tensor_metadata(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_metadata(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_metadata(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_shape_pipeline
torch::experimental::Tensor cpp_experimental_tensor_shape_pipeline(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_shape_pipeline(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_shape_pipeline(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_reductions
torch::experimental::Tensor cpp_experimental_tensor_reductions(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_reductions(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_reductions(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_comparisons
torch::experimental::Tensor cpp_experimental_tensor_comparisons(torch::experimental::Tensor first, torch::experimental::Tensor second);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_comparisons(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type first(firstSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_comparisons(first, second));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_namespace_out_overload
torch::experimental::Tensor cpp_experimental_namespace_out_overload(torch::experimental::Tensor first, torch::experimental::Tensor second);
RcppExport SEXP _torchextensiontest_cpp_experimental_namespace_out_overload(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type first(firstSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_namespace_out_overload(first, second));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_to_dtype
torch::experimental::Tensor cpp_experimental_tensor_to_dtype(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_to_dtype(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_to_dtype(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_autograd_state
torch::experimental::Tensor cpp_experimental_tensor_autograd_state(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_autograd_state(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_autograd_state(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_negative_indices
torch::experimental::Tensor cpp_experimental_edge_negative_indices(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_negative_indices(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_negative_indices(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_transpose_is_contiguous
bool cpp_experimental_edge_transpose_is_contiguous(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_transpose_is_contiguous(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_transpose_is_contiguous(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_make_contiguous
torch::experimental::Tensor cpp_experimental_edge_make_contiguous(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_make_contiguous(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_make_contiguous(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_clone_isolation
torch::experimental::Tensor cpp_experimental_edge_clone_isolation(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_clone_isolation(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_clone_isolation(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_view_aliasing
torch::experimental::Tensor cpp_experimental_edge_view_aliasing(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_view_aliasing(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_view_aliasing(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_zero_sized
torch::experimental::Tensor cpp_experimental_edge_zero_sized();
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_zero_sized() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_zero_sized());
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_scalar_tensor
torch::experimental::Tensor cpp_experimental_edge_scalar_tensor(double value);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_scalar_tensor(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_scalar_tensor(value));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_temporary_lifetime
torch::experimental::Tensor cpp_experimental_edge_temporary_lifetime(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_temporary_lifetime(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_temporary_lifetime(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_requires_grad_creation
torch::experimental::Tensor cpp_experimental_edge_requires_grad_creation();
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_requires_grad_creation() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_requires_grad_creation());
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_edge_invalid_reshape
torch::experimental::Tensor cpp_experimental_edge_invalid_reshape(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_edge_invalid_reshape(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_edge_invalid_reshape(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_scalar_overloads
torch::experimental::Tensor cpp_experimental_tensor_scalar_overloads(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_scalar_overloads(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_scalar_overloads(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_integral_scalar_overloads
torch::experimental::Tensor cpp_experimental_tensor_integral_scalar_overloads(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_integral_scalar_overloads(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_integral_scalar_overloads(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_inplace_overloads
torch::experimental::Tensor cpp_experimental_tensor_inplace_overloads(torch::experimental::Tensor input, torch::experimental::Tensor other);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_inplace_overloads(SEXP inputSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_inplace_overloads(input, other));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_cat_overloads
torch::experimental::Tensor cpp_experimental_tensor_cat_overloads(torch::experimental::Tensor first, torch::experimental::Tensor second);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_cat_overloads(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type first(firstSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_cat_overloads(first, second));
    return rcpp_result_gen;
END_RCPP
}
// cpp_public_torch_namespace_functions
torch::experimental::Tensor cpp_public_torch_namespace_functions(torch::experimental::Tensor first, torch::experimental::Tensor second);
RcppExport SEXP _torchextensiontest_cpp_public_torch_namespace_functions(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type first(firstSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_public_torch_namespace_functions(first, second));
    return rcpp_result_gen;
END_RCPP
}
// cpp_public_torch_nested_namespace_functions
torch::experimental::Tensor cpp_public_torch_nested_namespace_functions(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_public_torch_nested_namespace_functions(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_public_torch_nested_namespace_functions(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_tensor_to_device
torch::experimental::Tensor cpp_experimental_tensor_to_device(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_tensor_to_device(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_tensor_to_device(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_creation_zeros
torch::experimental::Tensor cpp_experimental_creation_zeros();
RcppExport SEXP _torchextensiontest_cpp_experimental_creation_zeros() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_creation_zeros());
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_creation_arange
torch::experimental::Tensor cpp_experimental_creation_arange();
RcppExport SEXP _torchextensiontest_cpp_experimental_creation_arange() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_creation_arange());
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_creation_eye
torch::experimental::Tensor cpp_experimental_creation_eye();
RcppExport SEXP _torchextensiontest_cpp_experimental_creation_eye() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_creation_eye());
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_creation_full_like
torch::experimental::Tensor cpp_experimental_creation_full_like(torch::experimental::Tensor input);
RcppExport SEXP _torchextensiontest_cpp_experimental_creation_full_like(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_creation_full_like(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_creation_random_sizes
std::vector<std::int64_t> cpp_experimental_creation_random_sizes();
RcppExport SEXP _torchextensiontest_cpp_experimental_creation_random_sizes() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_creation_random_sizes());
    return rcpp_result_gen;
END_RCPP
}
// zeros
torch::experimental::Tensor zeros(int rows, int cols);
RcppExport SEXP _torchextensiontest_zeros(SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(zeros(rows, cols));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_nn2poly_linear
torch::experimental::Tensor cpp_experimental_nn2poly_linear(torch::experimental::Tensor layer, torch::experimental::Tensor coefficients);
RcppExport SEXP _torchextensiontest_cpp_experimental_nn2poly_linear(SEXP layerSEXP, SEXP coefficientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type layer(layerSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type coefficients(coefficientsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_nn2poly_linear(layer, coefficients));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_nn2poly_add_partition
torch::experimental::Tensor cpp_experimental_nn2poly_add_partition(torch::experimental::Tensor matrix, std::int64_t column, double scalar, torch::experimental::Tensor values);
RcppExport SEXP _torchextensiontest_cpp_experimental_nn2poly_add_partition(SEXP matrixSEXP, SEXP columnSEXP, SEXP scalarSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< std::int64_t >::type column(columnSEXP);
    Rcpp::traits::input_parameter< double >::type scalar(scalarSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_nn2poly_add_partition(matrix, column, scalar, values));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_nn2poly_add_poly_eval
torch::experimental::Tensor cpp_experimental_nn2poly_add_poly_eval(torch::experimental::Tensor matrix, std::int64_t column, torch::experimental::Tensor input, std::int64_t input_column, std::vector<double> coefficients);
RcppExport SEXP _torchextensiontest_cpp_experimental_nn2poly_add_poly_eval(SEXP matrixSEXP, SEXP columnSEXP, SEXP inputSEXP, SEXP input_columnSEXP, SEXP coefficientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< std::int64_t >::type column(columnSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::int64_t >::type input_column(input_columnSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type coefficients(coefficientsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_nn2poly_add_poly_eval(matrix, column, input, input_column, coefficients));
    return rcpp_result_gen;
END_RCPP
}
// cpp_experimental_nn2poly_accumulate_partition
torch::experimental::Tensor cpp_experimental_nn2poly_accumulate_partition(torch::experimental::Tensor matrix, std::int64_t output_column, std::vector<std::int64_t> input_columns, std::vector<double> multipliers, torch::experimental::Tensor output);
RcppExport SEXP _torchextensiontest_cpp_experimental_nn2poly_accumulate_partition(SEXP matrixSEXP, SEXP output_columnSEXP, SEXP input_columnsSEXP, SEXP multipliersSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< std::int64_t >::type output_column(output_columnSEXP);
    Rcpp::traits::input_parameter< std::vector<std::int64_t> >::type input_columns(input_columnsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type multipliers(multipliersSEXP);
    Rcpp::traits::input_parameter< torch::experimental::Tensor >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_experimental_nn2poly_accumulate_partition(matrix, output_column, input_columns, multipliers, output));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_torchextensiontest_cpp_experimental_tensor_relu_reshape", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_relu_reshape, 1},
    {"_torchextensiontest_cpp_experimental_tensor_sizes", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_sizes, 1},
    {"_torchextensiontest_cpp_experimental_tensor_generated_methods", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_generated_methods, 1},
    {"_torchextensiontest_cpp_experimental_tensor_native_integer_argument", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_native_integer_argument, 1},
    {"_torchextensiontest_cpp_experimental_tensor_native_bool_return", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_native_bool_return, 1},
    {"_torchextensiontest_cpp_experimental_tensor_metadata", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_metadata, 1},
    {"_torchextensiontest_cpp_experimental_tensor_shape_pipeline", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_shape_pipeline, 1},
    {"_torchextensiontest_cpp_experimental_tensor_reductions", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_reductions, 1},
    {"_torchextensiontest_cpp_experimental_tensor_comparisons", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_comparisons, 2},
    {"_torchextensiontest_cpp_experimental_namespace_out_overload", (DL_FUNC) &_torchextensiontest_cpp_experimental_namespace_out_overload, 2},
    {"_torchextensiontest_cpp_experimental_tensor_to_dtype", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_to_dtype, 1},
    {"_torchextensiontest_cpp_experimental_tensor_autograd_state", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_autograd_state, 1},
    {"_torchextensiontest_cpp_experimental_edge_negative_indices", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_negative_indices, 1},
    {"_torchextensiontest_cpp_experimental_edge_transpose_is_contiguous", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_transpose_is_contiguous, 1},
    {"_torchextensiontest_cpp_experimental_edge_make_contiguous", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_make_contiguous, 1},
    {"_torchextensiontest_cpp_experimental_edge_clone_isolation", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_clone_isolation, 1},
    {"_torchextensiontest_cpp_experimental_edge_view_aliasing", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_view_aliasing, 1},
    {"_torchextensiontest_cpp_experimental_edge_zero_sized", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_zero_sized, 0},
    {"_torchextensiontest_cpp_experimental_edge_scalar_tensor", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_scalar_tensor, 1},
    {"_torchextensiontest_cpp_experimental_edge_temporary_lifetime", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_temporary_lifetime, 1},
    {"_torchextensiontest_cpp_experimental_edge_requires_grad_creation", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_requires_grad_creation, 0},
    {"_torchextensiontest_cpp_experimental_edge_invalid_reshape", (DL_FUNC) &_torchextensiontest_cpp_experimental_edge_invalid_reshape, 1},
    {"_torchextensiontest_cpp_experimental_tensor_scalar_overloads", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_scalar_overloads, 1},
    {"_torchextensiontest_cpp_experimental_tensor_integral_scalar_overloads", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_integral_scalar_overloads, 1},
    {"_torchextensiontest_cpp_experimental_tensor_inplace_overloads", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_inplace_overloads, 2},
    {"_torchextensiontest_cpp_experimental_tensor_cat_overloads", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_cat_overloads, 2},
    {"_torchextensiontest_cpp_public_torch_namespace_functions", (DL_FUNC) &_torchextensiontest_cpp_public_torch_namespace_functions, 2},
    {"_torchextensiontest_cpp_public_torch_nested_namespace_functions", (DL_FUNC) &_torchextensiontest_cpp_public_torch_nested_namespace_functions, 1},
    {"_torchextensiontest_cpp_experimental_tensor_to_device", (DL_FUNC) &_torchextensiontest_cpp_experimental_tensor_to_device, 1},
    {"_torchextensiontest_cpp_experimental_creation_zeros", (DL_FUNC) &_torchextensiontest_cpp_experimental_creation_zeros, 0},
    {"_torchextensiontest_cpp_experimental_creation_arange", (DL_FUNC) &_torchextensiontest_cpp_experimental_creation_arange, 0},
    {"_torchextensiontest_cpp_experimental_creation_eye", (DL_FUNC) &_torchextensiontest_cpp_experimental_creation_eye, 0},
    {"_torchextensiontest_cpp_experimental_creation_full_like", (DL_FUNC) &_torchextensiontest_cpp_experimental_creation_full_like, 1},
    {"_torchextensiontest_cpp_experimental_creation_random_sizes", (DL_FUNC) &_torchextensiontest_cpp_experimental_creation_random_sizes, 0},
    {"_torchextensiontest_zeros", (DL_FUNC) &_torchextensiontest_zeros, 2},
    {"_torchextensiontest_cpp_experimental_nn2poly_linear", (DL_FUNC) &_torchextensiontest_cpp_experimental_nn2poly_linear, 2},
    {"_torchextensiontest_cpp_experimental_nn2poly_add_partition", (DL_FUNC) &_torchextensiontest_cpp_experimental_nn2poly_add_partition, 4},
    {"_torchextensiontest_cpp_experimental_nn2poly_add_poly_eval", (DL_FUNC) &_torchextensiontest_cpp_experimental_nn2poly_add_poly_eval, 5},
    {"_torchextensiontest_cpp_experimental_nn2poly_accumulate_partition", (DL_FUNC) &_torchextensiontest_cpp_experimental_nn2poly_accumulate_partition, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_torchextensiontest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
