name: "Depending on OS we have different ways of installing R"
description: "Handles custom installation of R"
inputs:
   r_version:
     required: true
     description: "the R version. passed to setup R in some cases."

runs:
  using: composite
  steps:
    
    - name: Grab Linux version
      id: linux-version
      if: ${{ runner.os == 'Linux'}}
      run: |
        LINUX_VERSION=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
        echo "linux_version=$(echo $LINUX_VERSION)" >> $GITHUB_OUTPUT      
      shell: bash

    - name: Make sure sudo is installed
      if: ${{ contains(steps.linux-version.outputs.linux_version, 'Ubuntu') }}
      run: |
        if ! command -v sudo &> /dev/null
        then
          DEBIAN_FRONTEND="noninteractive" apt-get update -y
          DEBIAN_FRONTEND="noninteractive" apt-get install -y sudo software-properties-common dialog apt-utils tzdata libpng-dev locales
        fi
      shell: bash

    - uses: r-lib/actions/setup-r@v2
      if: ${{ !contains(steps.linux-version.outputs.linux_version, 'CentOS') && inputs.r_version != '' }}
      with:
        r-version: ${{ inputs.r_version }}

    - name: Setup R libraries
      # On CentOS R is not fully configured, so we do it here.
      if: ${{ contains(steps.linux-version.outputs.linux_version, 'CentOS') }}
      run: |
        echo "options(repos = c(CRAN = 'https://cran.rstudio.com'))" > .Rprofile
        sudo yum install -y openssl-devel
      shell: bash

    - uses: r-lib/actions/setup-pandoc@v2
      if: ${{ !contains(steps.linux-version.outputs.linux_version, 'CentOS') && inputs.r_version != '' }}

    - name: Setup parallel compilation
      run: |
        cores=$(Rscript -e "cat(parallel::detectCores())")
        path="$HOME/.R/Makevars"
        mkdir -p "$HOME/.R"
        if [ ! -f $path ]
        then
          touch $path
          echo "MAKEFLAGS=-j$cores" >> $path
        fi
      shell: bash