#' Generates all torch autogenerated code.
#'
#' @param path the path to the root odf the torch package.
#'
#' @export
generate <- function(path) {
  cat("Starting code generation ...\n")
  cpp(path)
  r(path)
  cat("Done!")
}
