
namespace_s4 <- function() {

  methods <- namespace_methods() %>%
    purrr::discard(~.x$name %in% namespace_s4_exceptions())

  tm <- namespace_methods()

  unq_names <- methods %>%
    purrr::map_chr(~.x$name) %>%
    unique() %>%
    purrr::map(~declarations_with_name(tm, .x))

  generics <- unq_names %>%
    purrr::map_chr(generic_s4_code)

  impl <- methods %>%
    purrr::map_chr(namespace_s4_code)


  code <- paste(
    c("# Autogenerated file", generics, impl),
    collapse = "\n\n"
  )

  code
}


#' Generates the definition of an S4 method
#'
#' @inheritParams method_cpp_code
#'
namespace_s4_code <- function(method) {
  glue::glue(
"
setMethod(
 f = '{namespace_s4_generic_name(method)}',
 signature = {method_s4_signature(method, namespace_methods())},
 definition = function({method_s4_impl_signature(method)}) {{
  {method_s4_impl_body(method, fun_name = namespace_cpp_name)}
 }})
"
  )
}

#' Get's the name of the generic function corresponding to the method
#'
#' @param method a single method or a list of methods.
#'
namespace_s4_generic_name <- function(method) {

  nm <- method[["name"]]

  if (is.null(nm))
    nm <- method[[1]]$name

  glue::glue("tch_{nm}")
}

namespace_s4_exceptions <- function() {
  c("_nnpack_available")
}

