
namespace_cpp <- function() {

  methods <- namespace_methods() %>%
    purrr::discard(~.x$name %in% namespace_cpp_exceptions()) %>%
    purrr::map_chr(namespace_cpp_code) %>%
    purrr::map_chr(~paste("// [[Rcpp::export]]\n", .x))

  code <- paste(
    c("// Autogenerated file", cpp_deps(), paste(methods)),
    collapse = "\n\n"
  )

  code
}

namespace_cpp_code <- function(method) {
  glue::glue("
     {method_cpp_return_type(method)} {namespace_cpp_name(method)} ({method_cpp_signature(method)}) {{
       {namespace_cpp_body(method)}
     }};
  ")
}

namespace_cpp_name <- function(method) {
  glue::glue("tch_{method$name}_{hash_arguments(method$arguments)}")
}

namespace_cpp_body <- function(method) {
  glue::glue(
    "
    {namespace_cpp_create_out(method)}
    {cpp_return_statement(method$returns)}
    "
  )
}

namespace_cpp_create_out <- function(method) {

  arguments <- method$arguments %>%
    purrr::map_chr(cpp_use_argument) %>%
    purrr::discard(is.na) %>%
    paste(collapse = ", ")

  out <- glue::glue("torch::{method$name}({arguments});")

  if (method$returns[[1]]$dynamic_type != "void")
    out <- paste0("auto r_out = ", out)

  out
}

namespace_cpp_exceptions <- function() {
  c("normal")
}

