name: "Uploads lantern artifacts to S3"
description: "Uploads lantern artifacts to S3"
inputs:
  fname:
    required: true
    description: "the filename that should be uploaded."
  aws_role_to_assume:
    required: true
    description: "Role ARN to be assumed"
  aws_region:
    required: true
    description: "Region id to be used"

runs:
  using: composite
  steps:

    - id: 'auth'
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        aws-region: ${{ inputs.aws_region }}

    - id: 'upload-file'
      run: |
        aws s3 cp src/lantern/build/${{ inputs.fname }} s3://torch-binaries/binaries/${{ github.sha }}/${{ inputs.fname }}

    - id: 'upload-latest'
      run: |
        aws s3 cp src/lantern/build/${{ inputs.fname }} s3://torch-binaries/binaries/${{ github.ref }}/latest/${{ inputs.fname }}
