# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tensor_from_r_ <- function(x, dim, dtype, device, requires_grad = FALSE) {
    .Call('_torch_tensor_from_r_', PACKAGE = 'torch', x, dim, dtype, device, requires_grad)
}

tensor_ <- function(x, dtype, device, requires_grad) {
    .Call('_torch_tensor_', PACKAGE = 'torch', x, dtype, device, requires_grad)
}

as_array_tensor_ <- function(x) {
    .Call('_torch_as_array_tensor_', PACKAGE = 'torch', x)
}

tensor_print_ <- function(x) {
    invisible(.Call('_torch_tensor_print_', PACKAGE = 'torch', x))
}

get_device_index <- function(device) {
    .Call('_torch_get_device_index', PACKAGE = 'torch', device)
}

get_device_type <- function(device) {
    .Call('_torch_get_device_type', PACKAGE = 'torch', device)
}

device_has_index <- function(device) {
    .Call('_torch_device_has_index', PACKAGE = 'torch', device)
}

device_is_cuda <- function(device) {
    .Call('_torch_device_is_cuda', PACKAGE = 'torch', device)
}

device_is_cpu <- function(device) {
    .Call('_torch_device_is_cpu', PACKAGE = 'torch', device)
}

device_equals <- function(device1, device2) {
    .Call('_torch_device_equals', PACKAGE = 'torch', device1, device2)
}

device_set_index <- function(device, index) {
    invisible(.Call('_torch_device_set_index', PACKAGE = 'torch', device, index))
}

device_from_r <- function(device, index) {
    .Call('_torch_device_from_r', PACKAGE = 'torch', device, index)
}

cpp_dtype_to_string <- function(dtype_ptr) {
    .Call('_torch_cpp_dtype_to_string', PACKAGE = 'torch', dtype_ptr)
}

cpp_torch_float32 <- function() {
    .Call('_torch_cpp_torch_float32', PACKAGE = 'torch')
}

cpp_torch_float64 <- function() {
    .Call('_torch_cpp_torch_float64', PACKAGE = 'torch')
}

cpp_torch_float16 <- function() {
    .Call('_torch_cpp_torch_float16', PACKAGE = 'torch')
}

cpp_torch_uint8 <- function() {
    .Call('_torch_cpp_torch_uint8', PACKAGE = 'torch')
}

cpp_torch_int8 <- function() {
    .Call('_torch_cpp_torch_int8', PACKAGE = 'torch')
}

cpp_torch_int16 <- function() {
    .Call('_torch_cpp_torch_int16', PACKAGE = 'torch')
}

cpp_torch_int32 <- function() {
    .Call('_torch_cpp_torch_int32', PACKAGE = 'torch')
}

cpp_torch_int64 <- function() {
    .Call('_torch_cpp_torch_int64', PACKAGE = 'torch')
}

cpp_torch_bool <- function() {
    .Call('_torch_cpp_torch_bool', PACKAGE = 'torch')
}

